Mappings:
  RegionsAMI:
    eu-west-1:
      "AMI": "ami-0db188056a6ff81ae"

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [ RegionsAMI, !Ref "AWS::Region", AMI ]
      InstanceType: t2.micro
      KeyName: "matchbuilder"
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - !ImportValue FlaskSecGroup
          SubnetId: !ImportValue FlaskSubnetPublic
      Tags:
        - Key: Name
          Value: Match Builder
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum install httpd -y
          service httpd start  
          echo "<html><body><h1>Testing!!!<h1></body></html>" > /var/www/html/index.html
Outputs:
  PublicIp:
    Description: 'EC2 Instance Private Ip'
    Value: !GetAtt EC2Instance.PrivateIp