Parameters:
  TemplateRootUrl:
    Description: "URL path to where template files are stoed in S3. Format: https://<BUCKET>.s3.<REGION>.amazonaws.com/<PATH>"
    Type: String
    Default: "https://cf-templates-match-builder-eu-west-1.s3.eu-west-1.amazonaws.com/match-builder/cf"

Resources:
  DynamoDb:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateRootUrl}/dynamodb.yaml"

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateRootUrl}/vpc.yaml"

  Subnets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateRootUrl}/subnets.yaml"
    DependsOn: VPC

  RouteTables:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateRootUrl}/routes.yaml"
    DependsOn: Subnets

  SecGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateRootUrl}/security_groups.yaml"
    DependsOn: VPC

#  NOTE: Deploys a single Ec2 instance, we will move on to deploying using EC2
#  Ec2:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: !Sub "${TemplateRootUrl}/ec2.yaml"
#    DependsOn: RouteTables

  FlaskECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateRootUrl}/ecs.yaml"
    DependsOn: RouteTables
