Parameters:
  TemplateRootUrl:
    Description: "URL path to where template files are stoed in S3. Format: https://<BUCKET>.s3.<REGION>.amazonaws.com/<PATH>"
    Type: String
    Default: "https://cf-templates-match-builder-eu-west-1.s3.eu-west-1.amazonaws.com/match-builder/cf"

Resources:
  DynamoDb:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateRootUrl}/dynamodb.yaml"

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateRootUrl}/vpc.yaml"

  Subnets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateRootUrl}/subnets.yaml"
    DependsOn: VPC

  SecGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateRootUrl}/security_groups.yaml"
      Parameters:
        FlaskVpc: !ImportValue "FlaskVpc"
    DependsOn: Subnets