Resources:
  FlaskSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !ImportValue "MatchBuilderVpc"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
#          This again is too open. In future will only be accessible from a load balancer
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          # Leaving open to anywhere -> would never do in production
          CidrIp: '0.0.0.0/0'

Outputs:
  FlaskSecGroup:
    Description: The ID of the security group for flask applications
    Value: !Ref FlaskSecGroup
    Export:
      Name: "FlaskSecGroup"